//
// automatically generated by spin2cpp v1.06 on Tue Mar 24 22:05:26 2015
// spin2cpp --ccode --gas --elf -o balapiller.elf -Os balapiller.spin 
//

#ifndef balapillerSpin_Class_Defined__
#define balapillerSpin_Class_Defined__

#include <stdint.h>
#include "VGA64_PIXEngine.h"
#include "FullDuplexSerial.h"

#define _Clkmode (1032)
#define _Xinfreq (5000000)
#define _Rx (31)
#define _Tx (30)
#define Not_at_boundary (0)
#define Tw (1)
#define Lw (2)
#define Bw (3)
#define Rw (4)
#define Nwc (5)
#define Swc (6)
#define Nec (7)
#define Sec (8)
#define Pad (9)
#define _Up (0)
#define _Dn (1)
#define _Lt (2)
#define _Rt (3)
#define Upchar (56)
#define Dnchar (50)
#define Ltchar (52)
#define Rtchar (54)
#define Up (1)
#define Down (2)
#define Left (3)
#define Right (4)
#define Pen_erase (0)
#define Pen_draw (1)
#define Screenwidth (160)
#define Screenheight (120)
#define Hph (8)
#define Goalwidth (16)
#define Padsur (144)
#define Padinc (4)
#define Ball_back_in_play_delay (3)
#define Ball_out_of_play (0)
#define Ball_in_play (1)
#define Ballsize (3)
#define Ballspeed (1024)
#define Ballratio (16)
#define Screen_top_offset (0)
#define Screen_bottom_offset (1)
#define Screen_left_offset (0)
#define Screen_right_offset (1)
#define Screenminx (0)
#define Screenmaxx (159)
#define Screenminy (0)
#define Screenmaxy (119)
#define Min_x_coordinate (3)
#define Max_x_coordinate (156)
#define Min_y_coordinate (3)
#define Max_y_coordinate (116)
#define _Pingroup (2)
#define _Switchrate (5)

typedef struct balapillerSpin {
  int32_t	Xball, Yball, Dirball;
  int32_t	Xpaddle, Ypaddle;
  int32_t	Bound, Peroff, Peron;
  int32_t	Deadballtime;
  int32_t	Ballinplay;
  char dummy__;
} balapillerSpin;

  int32_t	balapillerSpin_Main(void);
  int32_t	balapillerSpin_Atboundary(void);
  int32_t	balapillerSpin_Changedirection(int32_t Whichboundary, int32_t Olddirection);
  int32_t	balapillerSpin_Moveball(void);
  int32_t	balapillerSpin_Whatkey(void);
  int32_t	balapillerSpin_Movepaddle(void);
  int32_t	balapillerSpin_Plotball(int32_t X, int32_t Y, int32_t K);
  int32_t	balapillerSpin_Drawpaddle(int32_t X, int32_t Y, int32_t K);
  int32_t	balapillerSpin_Getkeypressed(void);
  int32_t	balapillerSpin_Newdirection(int32_t Whichkey, int32_t Olddirection);
  int32_t	balapillerSpin_Setnewball(int32_t Olddirection);
#endif
