//
// automatically generated by spin2cpp v1.06 on Tue Mar 24 22:05:26 2015
// spin2cpp --ccode --gas --elf -o balapiller.elf -Os balapiller.spin 
//

#include <propeller.h>
#include "balapiller.h"

#ifdef __GNUC__
#define INLINE__ static inline
#define PostEffect__(X, Y) __extension__({ int32_t tmp__ = (X); (X) = (Y); tmp__; })
#else
#define INLINE__ static
static int32_t tmp__;
#define PostEffect__(X, Y) (tmp__ = (X), (X) = (Y), tmp__)
#define waitcnt(n) _waitcnt(n)
#define locknew() _locknew()
#define lockret(i) _lockret(i)
#define lockset(i) _lockset(i)
#define lockclr(i) _lockclr(i)
#define coginit(id, code, par) _coginit((unsigned)(par)>>2, (unsigned)(code)>>2, id)
#define cognew(code, par) coginit(0x8, (code), (par))
#define cogstop(i) _cogstop(i)
#endif

static balapillerSpin thisobj;
int32_t balapillerSpin_Main(void)
{
  int32_t	I, Lastx, Lasty, Startballdir;
  FullDuplexSerial_Start(_Rx, _Tx, 0, 19200);
  if (!(VGA64_PIXEngine_Pixenginestart(_Pingroup))) {
    clkset(0x80, 0);
  }
  waitcnt(((CLKFREQ * 2) + CNT));
  Startballdir = 1;
  thisobj.Xball = (Screenwidth - (Screenwidth / 2));
  thisobj.Yball = (Screenheight / 2);
  thisobj.Dirball = _Up;
  balapillerSpin_Plotball(thisobj.Xball, thisobj.Yball, Pen_draw);
  thisobj.Ballinplay = Ball_in_play;
  thisobj.Peron = (Ballspeed / Ballratio);
  thisobj.Peroff = (Ballspeed - (Ballspeed / Ballratio));
  thisobj.Xpaddle = (Screenwidth - Goalwidth);
  thisobj.Ypaddle = (Screenheight / 2);
  Lasty = thisobj.Ypaddle;
  balapillerSpin_Drawpaddle(thisobj.Xpaddle, thisobj.Ypaddle, Pen_draw);
  while (1) {
    balapillerSpin_Movepaddle();
    if (Lasty != thisobj.Ypaddle) {
      balapillerSpin_Drawpaddle(thisobj.Xpaddle, Lasty, Pen_erase);
      balapillerSpin_Drawpaddle(thisobj.Xpaddle, thisobj.Ypaddle, Pen_draw);
      Lasty = thisobj.Ypaddle;
    }
    thisobj.Bound = balapillerSpin_Atboundary();
    if (thisobj.Bound != Not_at_boundary) {
      thisobj.Dirball = balapillerSpin_Changedirection(thisobj.Bound, thisobj.Dirball);
      if (thisobj.Ballinplay == Ball_in_play) {
        balapillerSpin_Plotball(thisobj.Xball, thisobj.Yball, Pen_erase);
        balapillerSpin_Moveball();
        balapillerSpin_Plotball(thisobj.Xball, thisobj.Yball, Pen_draw);
        waitcnt(((CLKFREQ / thisobj.Peron) + CNT));
      } else {
        if (thisobj.Deadballtime < CNT) {
          thisobj.Ballinplay = Ball_in_play;
          (Startballdir++);
          thisobj.Xball = (Screenwidth - (Screenwidth / 2));
          thisobj.Yball = (Screenheight / 2);
          if (Startballdir & 0x1) {
            thisobj.Dirball = _Up;
          } else {
            thisobj.Dirball = (-Up);
          }
          balapillerSpin_Plotball(thisobj.Xball, thisobj.Yball, Pen_draw);
        }
      }
    } else {
      thisobj.Ballinplay = Ball_out_of_play;
      balapillerSpin_Plotball(thisobj.Xball, thisobj.Yball, Pen_erase);
      thisobj.Xball = (Screenwidth - (Screenwidth / 2));
      thisobj.Yball = (Screenheight / 2);
      thisobj.Deadballtime = ((CLKFREQ * Ball_back_in_play_delay) + CNT);
    }
  }
  return 0;
}

int32_t balapillerSpin_Atboundary(void)
{
  int32_t Theboundary = 0;
  if ((thisobj.Xball == Min_x_coordinate) && (thisobj.Yball == Min_y_coordinate)) {
    Theboundary = Nwc;
  } else {
    if ((thisobj.Xball == Min_x_coordinate) && (thisobj.Yball == Max_y_coordinate)) {
      Theboundary = Swc;
    } else {
      if ((thisobj.Xball == Max_x_coordinate) && (thisobj.Yball == Min_y_coordinate)) {
        Theboundary = Nec;
      } else {
        if ((thisobj.Xball == Max_x_coordinate) && (thisobj.Yball == Max_y_coordinate)) {
          Theboundary = Sec;
        } else {
          if (thisobj.Xball == Min_x_coordinate) {
            Theboundary = Lw;
          } else {
            if (thisobj.Xball == Max_x_coordinate) {
              Theboundary = Rw;
            } else {
              if (thisobj.Yball == Min_y_coordinate) {
                Theboundary = Tw;
              } else {
                if (thisobj.Yball == Max_y_coordinate) {
                  Theboundary = Bw;
                } else {
                  if (thisobj.Xball == ((Padsur - Ballsize) - 1)) {
                    if ((thisobj.Yball < (thisobj.Ypaddle + Hph)) && (thisobj.Yball > (thisobj.Ypaddle - Hph))) {
                      Theboundary = Pad;
                    }
                  } else {
                    Theboundary = Not_at_boundary;
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  return Theboundary;
}

int32_t balapillerSpin_Changedirection(int32_t Whichboundary, int32_t Olddirection)
{
  int32_t Newdirection = 0;
  if (Whichboundary == Tw) {
    if (Olddirection == ) {
      Newdirection = ;
    } else {
      Newdirection = ;
    }
  } else if (Whichboundary == Lw) {
    if (Olddirection == ) {
      Newdirection = ;
    } else {
      Newdirection = ;
    }
  } else if (Whichboundary == Bw) {
    if (Olddirection == ) {
      Newdirection = ;
    } else {
      Newdirection = ;
    }
  } else if (Whichboundary == Rw || Whichboundary == Pad) {
    if (Olddirection == ) {
      Newdirection = ;
    } else {
      Newdirection = ;
    }
  } else if (Whichboundary == Nwc) {
    Newdirection = ;
  } else if (Whichboundary == Swc) {
    Newdirection = ;
  } else if (Whichboundary == Nec) {
    Newdirection = ;
  } else if (Whichboundary == Sec) {
    Newdirection = ;
  }
  return Newdirection;
}

int32_t balapillerSpin_Moveball(void)
{
  if (thisobj.Dirball == _Up) {
    thisobj.Yball = (thisobj.Yball - 2);
  } else if (thisobj.Dirball == _Dn) {
    thisobj.Yball = (thisobj.Yball + 2);
  } else if (thisobj.Dirball == _Lt) {
    thisobj.Xball = (thisobj.Xball - 2);
  } else if (thisobj.Dirball == _Rt) {
    thisobj.Xball = (thisobj.Xball + 2);
  }
  return 0;
}

int32_t balapillerSpin_Whatkey(void)
{
  int32_t	Updown;
  Updown = FullDuplexSerial_Rxcheck();
  if (Updown == Upchar) {
    Updown = Up;
  } else if (Updown == Dnchar) {
    Updown = Down;
  } else if (Updown == Ltchar) {
    Updown = Left;
  } else if (Updown == Rtchar) {
    Updown = Right;
  } else if (1) {
    Updown = 0;
  }
  return Updown;
}

int32_t balapillerSpin_Movepaddle(void)
{
  int32_t	Paddir;
  Paddir = balapillerSpin_Whatkey();
  if (Paddir == Up) {
    if (((thisobj.Ypaddle - Hph) - 1) > (0 + Padinc)) {
      thisobj.Ypaddle = (thisobj.Ypaddle - Padinc);
    }
  } else if (Paddir == Down) {
    if (((thisobj.Ypaddle + Hph) + 1) < (Screenmaxy - Padinc)) {
      thisobj.Ypaddle = (thisobj.Ypaddle + Padinc);
    }
  } else if (1) {
  }
  return 0;
}

int32_t balapillerSpin_Plotball(int32_t X, int32_t Y, int32_t K)
{
  if (K == Pen_erase) {
    VGA64_PIXEngine_Plotbox(VGA64_PIXEngine_Displaycolor(0, 0, 0), (X - 1), (Y - 1), (X + 1), (Y + 1));
  } else if (K == Pen_draw) {
    VGA64_PIXEngine_Plotbox(VGA64_PIXEngine_Displaycolor(3, 2, 1), (X - 1), (Y - 1), (X + 1), (Y + 1));
  }
  return 0;
}

int32_t balapillerSpin_Drawpaddle(int32_t X, int32_t Y, int32_t K)
{
  if (K == Pen_erase) {
    VGA64_PIXEngine_Plotbox(VGA64_PIXEngine_Displaycolor(0, 0, 0), (X - 1), (Y - Hph), (X + 1), (Y + Hph));
  } else if (K == Pen_draw) {
    VGA64_PIXEngine_Plotbox(VGA64_PIXEngine_Displaycolor(3, 2, 1), (X - 1), (Y - Hph), (X + 1), (Y + Hph));
  }
  return 0;
}

int32_t balapillerSpin_Getkeypressed(void)
{
  int32_t	Updown;
  Updown = FullDuplexSerial_Rxcheck();
  if (Updown == Upchar) {
    Updown = Up;
  } else if (Updown == Dnchar) {
    Updown = Down;
  } else if (Updown == Ltchar) {
    Updown = Left;
  } else if (Updown == Rtchar) {
    Updown = Right;
  } else if (1) {
    Updown = 0;
  }
  return Updown;
}

int32_t balapillerSpin_Newdirection(int32_t Whichkey, int32_t Olddirection)
{
  int32_t Newdirection = 0;
  if (Whichkey == Up) {
    if (Olddirection != _Up) {
      (++);
      Newdirection = _Up;
    }
  } else if (Whichkey == Down) {
    if (Olddirection != _Dn) {
      (++);
      Newdirection = _Dn;
    }
  } else if (Whichkey == Left) {
    if (Olddirection != _Lt) {
      (++);
      Newdirection = _Lt;
    }
  } else if (Whichkey == Right) {
    if (Olddirection != _Rt) {
      (++);
      Newdirection = _Rt;
    }
  } else if (1) {
    return Olddirection;
  }
  return Newdirection;
}

int32_t balapillerSpin_Setnewball(int32_t Olddirection)
{
  return 0;
}


int main() {
  return balapillerSpin_Main();
}
